system:
  random_seed: 1
  mindspore_seed: 1
  numpy_seed: 1
  context_mode: "graph_mode"
  graph_kernel_flags: null


dataset:
  dataset_name: "kodak"
  input_path: "/data/LLVT/Tunable_Conv/data/kodak"
  eval_batch_size: 1
  num_frames: 0
  scale: 4
  dataset_sink_mode: False
  num_parallel_workers: 1


model:
  name: "tunable_swinir"
  load_path: "/data/LLVT/Tunable_Conv/ckpt/t_swinir_sr4_ms.ckpt"
  img_channels: 3
  window_size: 8
  depths: [6, 6, 6, 6, 6, 6]
  num_heads: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  mlp_ratio: 2.0
  resi_connection: "1conv"
  num_params: 2
  mode: "mlp"
  upsampler: "pixelshuffle"
  upscale: 4

  params: [1.0, 0.0]


loss:
  name: "MSELoss"
  loss_scale: 1.0
  amp_level: "O0"

scheduler:
  base_lr: 0.00001
  min_lr: 1e-08
  name: "cosine_annealing"

  weight_decay: 0
  warmup_epochs: 0
  warmup_factor: 1.0

# Optimizer options
optimizer:
  name: "Adam"
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.999


# Metric options
metric:
  PSNR:
    reduction: 'avg'
    crop_border: 4
    input_order: 'CHW'
    convert_to: 'y'
  SSIM:
    reduction: 'avg'
    crop_border: 4
    input_order: 'CHW'
    convert_to: 'y'

test_pipeline: null
