# ==============================================================================
system:
  random_seed: null
  mindspore_seed: null
  numpy_seed: null
  context_mode: "graph_mode"
  graph_kernel_flags: null

model:
  name: "ttvsr"
  # Pretrained weights
  load_path: "/data/LLVT/TTVSR/ckpt/TTVSR_REDS.ckpt"
  spynet_load_path: "/data/LLVT/TTVSR/ckpt/spynet_20210409-c6c1bd09.ckpt"
  mid_channels: 64
  num_blocks: 60
  stride: 4

# Dataset options
dataset:
  dataset_name: "reds"
  input_path: "/data/LLVT/TTVSR/data/REDS/"
  train_annotation: 'REDS266.txt'
  test_annotation: 'REDS4.txt'
  gt_subdir: 'trainval_sharp_HR/'
  lq_subdir: 'trainval_sharp_bicubic/X4'
  batch_size: 4  # for all GPUs
  lr_type: "bicubic"
  scale: 4
  dataset_sink_mode: False
  num_frames: 10
  num_samples: null
  eval_batch_size: 1
  num_parallel_workers: 8


# Common training options
loss:
  name: "CharbonnierLoss"
  weight: 1.0
  amp_level: 'O0'
  loss_scale: 1000.0

# Optimizer options
optimizer:
  name: "Adam"
  learning_rate: 0.0002
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.99

# Scheduler options
scheduler:
  name: "cosine_annealing_warm_restarts_lr"
  base_lr: 2.0e-4
  min_lr: 1.0e-7
  warmup: linear
  warmup_epochs: 1
  warmup_factor: 0.001
  warmup_base_lr: 2.0e-4
  t_mult: 1

extra_scheduler:
  name: "cosine_annealing_warm_restarts_lr"
  lr_mul: 0.125
  warmup: linear
  warmup_epochs: 1 # freeze epochs
  warmup_factor: 0.0 # freeze
  warmup_base_lr: 0.0 # freeze
  t_mult: 1
  param_prefixes: ["spynet"]

# Metric options
metric:
  PSNR:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null
  SSIM:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null

train_params:
  epoch_size: 25000
  need_val: True
  keep_checkpoint_max: 60
  save_epoch_frq: 1
  eval_frequency: 1
  print_frequency: 1
  ckpt_save_dir: "./ckpt/ttvsr"

# Preprocessing pipeline and augmentations for training phase
train_pipeline:
  - GenerateSegmentIndices:
      interval_list: 1
  - TemporalReverse:
      keys: [ 'lq', 'gt' ]
      reverse_ratio: 0.5
  - LoadImageFromFileList:
      keys: 'lq'
      channel_order: 'rgb'
      io_backend: 'disk'
  - LoadImageFromFileList:
      keys: 'lq'
      channel_order: 'rgb'
      io_backend: 'disk'
  - PairedRandomCrop:
      gt_patch_size: 256
  - RescaleToZeroOne:
      keys: [ 'lq', 'gt' ]
  - Flip:
      keys: [ 'lq', 'gt' ]
      direction: 'horizontal'
      flip_ratio: 0.5
  - Flip:
      keys: [ 'lq', 'gt' ]
      direction: 'vertical'
      flip_ratio: 0.5
  - RandomTransposeHW:
      keys: [ 'lq', 'gt' ]
      transpose_ratio: 0.5
  - FramesToTensor:
      keys: [ 'lq', 'gt' ]
  - Collect:
      keys: [ 'lq', 'gt' ]

# Preprocessing pipeline and augmentations for evaluation phase
test_pipeline:
  - GenerateSegmentIndices:
      interval_list: 1
  - LoadImageFromFileList:
      keys: 'lq'
      channel_order: 'rgb'
      io_backend: 'disk'
  - LoadImageFromFileList:
      keys: 'lq'
      channel_order: 'rgb'
      io_backend: 'disk'
  - RescaleToZeroOne:
      keys: [ 'lq', 'gt' ]
  - FramesToTensor:
      keys: [ 'lq', 'gt' ]
  - Collect:
      keys: [ 'lq', 'gt' ]
