system:
  random_seed: null
  mindspore_seed: null
  numpy_seed: null
  context_mode: "graph_mode"
  graph_kernel_flags: null

model:
  name: "basicvsr"
  # Pretrained weights
  load_path: "/data/LLVT/Basic_VSR/ckpt/basicvsr_ascend_vimeo90k_psnr37.23_20221214.ckpt"
  spynet_load_path: "/data/LLVT/Basic_VSR/ckpt/spynet_20210409-c6c1bd09.ckpt"

# Dataset options
dataset:
  dataset_name: "vimeo_super_resolution"
  input_path: "/data/LLVT/Basic_VSR/data/mini_vimeo_super_resolution_test"
  train_annotation: 'sep_trainlist.txt'
  test_annotation: 'sep_testlist.txt'
  gt_subdir: 'sequences'
  lr_subdir: 'BIx4'
  batch_size: 1  # for all GPUs
  lr_type: "bicubic"
  scale: 4
  max_rowsize: 32
  dataset_sink_mode: False
  num_frames: 7
  num_samples: null
  eval_batch_size: 1
  num_parallel_workers: 1

# Common training options
loss:
  name: "CharbonnierLoss"
  amp_level: "O0"
  loss_scale: 1000.0 # for ['O2', 'O3', 'auto']

# Metric options
metric:
  PSNR:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: 'y'
    process_middle_image: [True, True]
  SSIM:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: 'y'
    process_middle_image: [True, True]

# Preprocessing pipeline and augmentations for training phase
train_pipeline:
  name: basicvsr
  pipeline:
    - RescaleToZeroOne:
        keys: [ 'lq', 'gt' ]
    - PairedRandomCrop:
        gt_patch_size: 256
    - RandomFlip:
        keys: [ 'lq', 'gt' ]
        flip_ratio: 0.5
        direction: 'horizontal'
    - RandomFlip:
        keys: [ 'lq', 'gt' ]
        flip_ratio: 0.5
        direction: 'vertical'
    - RandomTransposeHW:
        keys: [ 'lq', 'gt' ]
        transpose_ratio: 0.5
    - MirrorSequence:
        keys: [ 'lq', 'gt' ]
    - Collect:
        keys: [ 'lq', 'gt' ]

# Preprocessing pipeline and augmentations for evaluation phase
test_pipeline:
  name: basicvsr
  pipeline:
    - RescaleToZeroOne:
        keys: [ 'lq', 'gt' ]
    - MirrorSequence:
        keys: [ 'lq', 'gt' ]
    - Collect:
        keys: [ 'lq', 'gt' ]

# Optimizations
optimization:
  precompute_grid: False
  spynet:
    base_resolution: [ [ 64, 64 ], [ 64, 128 ] ]
    levels: 6
  basicvsr:
    base_resolution: [ [ 64, 64 ], [ 64, 112 ] ]
    levels: 1
  eliminate_gradient_for_gather: False

export_helper: basicvsr
