system:
  random_seed: null
  mindspore_seed: null
  numpy_seed: null
  context_mode: "graph_mode"
  graph_kernel_flags: null

model:
  name: "basicvsr_plus_plus_light"
  load_path: "/data/LLVT/BasicVSR_plus_plus/ckpt/basicvsr_plus_plus_light_ascend_davis2017_psnr30.01_20230627.ckpt"
  params:
    mid_channels: 64
    num_blocks: 15
    num_blocks_align: 5
    is_low_res_input: False
    upsample_blocks_last: False
    has_bias: False
    activation: "ReLU"
    pad_input: True

# Dataset options
dataset:
  dataset_name: "set8"
  input_path: "/data/LLVT/BasicVSR_plus_plus/data/Set8/"
  return_paths: True
  num_frames: null
  scale: 1

  num_samples: null
  eval_batch_size: 1

  num_parallel_workers: 4
  max_rowsize: 128
  python_multiprocessing: True
  dataset_sink_mode: False
  transform_while_batching: False
  profile_preproc_pipeline: False

# Common training options
loss:
  name: "CharbonnierLoss"
  weight: 1.0
  amp_level: "O2"
  loss_scale: 1000.0 # for ['O2', 'O3', 'auto']

# Metric options
metric:
  PSNR:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null
    process_middle_image: [False, False]
  SSIM:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: null
    process_middle_image: [False, False]

val_params:
  img_save_directory: "/tmp/vdn_res"
  save_bgr: True


# Preprocessing pipeline and augmentations for evaluation phase
test_pipeline:
  name: basicvsr_plus_plus_light
  pipeline:
    - LoadImageFromFileList:
        key: 'gt'
        channel_order: 'rgb'
    - RescaleToZeroOne:
        keys: ['gt']
    - CopyValues:
        src_keys: ['gt']
        dst_keys: ['lq']
    - RandomNoise:
        keys: ['lq']
        params:
          noise_type: ['gaussian']
          noise_prob: [1]
          gaussian_sigma: [50, 50]
          gaussian_gray_noise_prob: 0
    - Collect:
        keys: [ 'lq', 'gt' ]
