system:
  random_seed: null
  mindspore_seed: null
  numpy_seed: null
  context_mode: "graph_mode"
  graph_kernel_flags: null

model:
  name: "rrdb"
  # Pretrained weights
  in_channels: 3
  out_channels: 3
  mid_channels: 64
  num_blocks: 8
  internal_ch: 32
  bias: true
  load_path: ""

# Dataset options
dataset:
  dataset_name: "df2k"
  input_path: ["/data/LLVT/RRDB/data/div2k", "/data/LLVT/RRDB/data/flickr2k"]
  batch_size: 128
  lr_type: "bicubic"
  scale: 4
  divisor: 4
  num_frames: 1
  max_rowsize: 64
  dataset_sink_mode: False
  eval_batch_size: 1
  num_parallel_workers: 1

val_dataset:
  dataset_name: "div2k"
  input_path: "/data/LLVT/RRDB/data/div2k"
  batch_size: 1
  lr_type: "bicubic"
  scale: 4
  divisor: 4
  num_frames: 1
  max_rowsize: 32
  dataset_sink_mode: False
  eval_batch_size: 1
  num_parallel_workers: 1

# Common training options
loss:
  name: "l1loss"
  weight: 1.0
  amp_level: "O0"
  loss_scale: 1000.0 # for ["O2", "O3", "auto"]

# Optimizer options
optimizer:
  name: "Adam"
  learning_rate: 2.2e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.99

# Scheduler options
scheduler:
  name: "cosine_annealing"
  base_lr: 2.2e-4
  min_lr: 1.0e-5
  warmup_epochs: 0
  warmup_factor: 0.0
  warmup_base_lr: 2.2e-4

# Metric options
metric:
  PSNR:
    reduction: "avg"
    crop_border: 0
    input_order: "CHW"
    convert_to: "y"
    process_middle_image: [False, False]
  SSIM:
    reduction: "avg"
    crop_border: 0
    input_order: "CHW"
    convert_to: "y"
    process_middle_image: [False, False]

train_params:
  epoch_size: 220
  need_val: True
  keep_checkpoint_max: 60
  save_epoch_frq: 10 # 9118
  eval_frequency: 10
  print_frequency: 100
  ckpt_save_dir: "./ckpt_rrdb_df2k-64ch"


# Preprocessing pipeline and augmentations for training phase
train_pipeline:
  name: rrdb
  pipeline:
    - PairedRandomCrop:
        gt_patch_size: 160
    - RandomFlip:
        keys: [ "lq", "gt" ]
        flip_ratio: 0.5
        direction: "horizontal"
    - RandomFlip:
        keys: [ "lq", "gt" ]
        flip_ratio: 0.5
        direction: "vertical"
    - RandomTransposeHW:
        keys: [ "lq", "gt" ]
        transpose_ratio: 0.5
    - RescaleToZeroOne:
        keys: [ "lq", "gt" ]
    - Collect:
        keys: [ "lq", "gt" ]

# Preprocessing pipeline and augmentations for evaluation phase
test_pipeline:
  name: rrdb
  pipeline:
    - RescaleToZeroOne:
        keys: [ "lq", "gt" ]
    - Collect:
        keys: [ "lq", "gt" ]
