system:
  random_seed: null
  mindspore_seed: null
  numpy_seed: null
  context_mode: "graph_mode"
  graph_kernel_flags: null

model:
  name: "basicvsr_plus_plus_light"
  load_path: null
  params:
    mid_channels: 64
    num_blocks: 7
    num_blocks_align: 5
    is_low_res_input: False
    upsample_blocks_last: False
    has_bias: False

# Dataset options
dataset:
  dataset_name: "ldv_v2"
  input_path: "/data/LLVT/BasicVSR_plus_plus/data/LDV_V2"
  resolution: null
  video_mode: True
  return_paths: False
  num_frames: 30
  scale: 1
  gt_subdir: 'train_gt'
  lr_subdir: 'train_lq'
  batch_size: 4
  num_samples: null
  eval_batch_size: 1
  num_parallel_workers: 1
  max_rowsize: 42
  python_multiprocessing: True
  dataset_sink_mode: True
  transform_while_batching: False

val_dataset:
  dataset_name: "ldv_v2"
  input_path: "/data/LLVT/BasicVSR_plus_plus/data/LDV_V2"
  return_paths: False
  num_frames: 30
  gt_subdir: 'valid_gt'
  lr_subdir: 'valid_lq'
  scale: 1
  num_samples: null
  eval_batch_size: 1
  num_parallel_workers: 1
  max_rowsize: 42
  python_multiprocessing: True
  dataset_sink_mode: False
  transform_while_batching: False

# Common training options
loss:
  name: "CharbonnierLoss"
  weight: 1.0
  amp_level: "O2"
  loss_scale: 1000.0 # for ['O2', 'O3', 'auto']

# Optimizer options
optimizer:
  name: "Adam"
  learning_rate: 1.0e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.99

# Scheduler options
scheduler:
  name: "warmup_cosine_annealing"
  base_lr: 1.0e-4
  min_lr: 1.0e-7
  warmup_epochs: 10
  warmup_factor: 1.e-3
  warmup_base_lr: 1.0e-4

# Metric options
metric:
  PSNR:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: 'y'
    process_middle_image: [False, False]
  SSIM:
    reduction: 'avg'
    crop_border: 0
    input_order: 'CHW'
    convert_to: 'y'
    process_middle_image: [False, False]

train_params:
  epoch_size: 5000  # Number of epochs to train.
  need_val: True
  keep_checkpoint_max: 60
  save_epoch_frq: 300  # equal to 1 epoch with batch size = 8 on Vimeo90K
  eval_frequency: 1
  print_frequency: 1
  ckpt_save_dir: "/cache/ckpt/basicvsr_plus_plus_light"
  profile:
    start: 2
    end: 3
    output_path: artifacts/profile


# Preprocessing pipeline and augmentations for training phase
train_pipeline:
  name: basicvsr
  pipeline:
    - RescaleToZeroOne:
        keys: ['lq', 'gt']
    - PairedRandomCrop:
        gt_patch_size: 256
    - RandomFlip:
        keys: ['lq', 'gt']
        flip_ratio: 0.5
        direction: 'horizontal'
    - RandomFlip:
        keys: [ 'lq', 'gt' ]
        flip_ratio: 0.5
        direction: 'vertical'
    - RandomTransposeHW:
        keys: ['lq', 'gt']
        transpose_ratio: 0.5
    - Collect:
        keys: ['lq', 'gt']

# Preprocessing pipeline and augmentations for evaluation phase
test_pipeline:
  name: basicvsr
  pipeline:
    - RescaleToZeroOne:
        keys: ['lq', 'gt']
    - Collect:
        keys: [ 'lq', 'gt' ]
